// <auto-generated />
using System;
using HFiles_Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HFilesBackend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102054120_ClinicEnquiryCoach_TableCreate")]
    partial class ClinicEnquiryCoachTableCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.BlacklistedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BlacklistedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("UserId");

                    b.ToTable("blacklisted_tokens");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Treatment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("VisitorPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("VisitorUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("AppointmentDate", "AppointmentTime")
                        .HasDatabaseName("idx_clinicappointments_date_time");

                    b.HasIndex("Status", "AppointmentDate")
                        .HasDatabaseName("idx_clinicappointments_status_date");

                    b.ToTable("clinicappointments", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicConsentForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("clinicconsentforms", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicEnquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("AppointmentTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<bool>("FirstCall")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FitnessGoal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Payment")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<bool>("SecondCall")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("UserId");

                    b.ToTable("clinicEnquiry");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicEnquiryCoach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("EnquiryId")
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("EnquiryId");

                    b.ToTable("ClinicEnquiryCoach");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicGoogleToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("primary");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("https://www.googleapis.com/auth/calendar");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Bearer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ClinicId", "IsActive");

                    b.HasIndex("IsActive", "TokenExpiry");

                    b.ToTable("clinic_google_tokens", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Coach")
                        .HasColumnType("longtext");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PromotedBy")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PromotedBy");

                    b.HasIndex("ClinicId", "DeletedBy")
                        .HasDatabaseName("IX_ClinicMembers_ClinicId_DeletedBy");

                    b.HasIndex("Id", "ClinicId", "DeletedBy")
                        .HasDatabaseName("IX_ClinicMembers_Id_ClinicId_DeletedBy");

                    b.HasIndex("UserId", "ClinicId", "DeletedBy")
                        .HasDatabaseName("IX_ClinicMembers_UserId_ClinicId_DeletedBy");

                    b.HasIndex("UserId", "ClinicId", "DeletedBy", "Role")
                        .HasDatabaseName("IX_ClinicMembers_UserId_ClinicId_DeletedBy_Role");

                    b.ToTable("clinicmembers", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicMemberRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("ClinicMemberId")
                        .HasColumnType("int");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReportUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ClinicMemberId");

                    b.HasIndex("UserId");

                    b.ToTable("clinicMemberRecords");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicOtpEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_ClinicOtpEntry_Email");

                    b.HasIndex("Email", "CreatedAt")
                        .HasDatabaseName("IX_ClinicOtpEntry_Email_CreatedAt");

                    b.HasIndex("Email", "CreatedAt", "ExpiryTime")
                        .HasDatabaseName("IX_ClinicOtpEntry_Email_CreatedAt_ExpiryTime");

                    b.ToTable("clinicotpentries", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicPatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HFID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VisitorPhoneNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HFID")
                        .HasDatabaseName("IX_ClinicPatients_HFID");

                    b.ToTable("clinicpatients", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicPatientMedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AggravatingFactors")
                        .HasColumnType("longtext");

                    b.Property<string>("Allergies")
                        .HasColumnType("longtext");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("ClinicPatientId")
                        .HasColumnType("int");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Diagnoses")
                        .HasColumnType("longtext");

                    b.Property<string>("Drugs")
                        .HasColumnType("longtext");

                    b.Property<string>("Duration")
                        .HasColumnType("longtext");

                    b.Property<string>("Frequency")
                        .HasColumnType("longtext");

                    b.Property<string>("GeneralExamination")
                        .HasColumnType("longtext");

                    b.Property<string>("Intensity")
                        .HasColumnType("longtext");

                    b.Property<string>("Investigations")
                        .HasColumnType("longtext");

                    b.Property<string>("Medical")
                        .HasColumnType("longtext");

                    b.Property<string>("NatureofPain")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PastHistory")
                        .HasColumnType("longtext");

                    b.Property<string>("PresentComplaints")
                        .HasColumnType("longtext");

                    b.Property<string>("ProvisionalDiagnosis")
                        .HasColumnType("longtext");

                    b.Property<string>("RelievingFacors")
                        .HasColumnType("longtext");

                    b.Property<string>("Surgical")
                        .HasColumnType("longtext");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ClinicPatientId");

                    b.ToTable("clinicpatientmedicalhistories");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicPatientRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("ClinicVisitId")
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<bool>("Is_Cansel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Is_editable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("Reference_Id")
                        .HasColumnType("int");

                    b.Property<bool>("SendToPatient")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UniqueRecordId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("payment_verify")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ClinicVisitId");

                    b.HasIndex("PatientId");

                    b.ToTable("clinicpatientrecords", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicPrescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("MedicationDosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Timing")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("clinicprescriptions", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicPrescriptionNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("clinicprescriptionnotes");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicRecordCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("clinicrecordcounters");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ClinicReference")
                        .HasColumnType("int");

                    b.Property<long>("CreatedAtEpoch")
                        .HasColumnType("bigint");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GoogleCalendarId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GoogleCredentialsPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("GoogleServiceAccountEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HFID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_ClinicSignup_Email");

                    b.HasIndex("HFID")
                        .IsUnique()
                        .HasDatabaseName("IX_ClinicSignup_HFID");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_ClinicSignup_Id");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_ClinicSignup_PhoneNumber");

                    b.HasIndex("Pincode")
                        .HasDatabaseName("IX_ClinicSignup_Pincode");

                    b.HasIndex("ClinicReference", "DeletedBy")
                        .HasDatabaseName("IX_ClinicSignup_ClinicReference_DeletedBy");

                    b.HasIndex("Id", "ClinicReference")
                        .HasDatabaseName("IX_ClinicSignup_Id_Reference");

                    b.HasIndex("Id", "Email", "DeletedBy")
                        .HasDatabaseName("IX_ClinicSignup_Id_Email_DeletedBy");

                    b.ToTable("clinicsignups", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicSuperAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<int>("IsMain")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId", "IsMain")
                        .HasDatabaseName("IX_ClinicSuperAdmins_ClinicId_IsMain");

                    b.HasIndex("Id", "UserId")
                        .HasDatabaseName("IX_ClinicSuperAdmins_Id_UserId");

                    b.HasIndex("UserId", "ClinicId", "IsMain")
                        .HasDatabaseName("IX_ClinicSuperAdmins_UserId_ClinicId_IsMain");

                    b.ToTable("clinicsuperadmins", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPerDay")
                        .HasColumnType("int");

                    b.Property<int?>("Sessions")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TreatmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("clinictreatments", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("ClinicPatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDate")
                        .HasDatabaseName("IX_ClinicVisits_AppointmentDate");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ClinicPatientId")
                        .HasDatabaseName("IX_ClinicVisits_ClinicPatientId");

                    b.HasIndex("AppointmentDate", "ClinicPatientId")
                        .HasDatabaseName("IX_ClinicVisits_Date_Patient");

                    b.ToTable("clinicvisits", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicVisitConsentForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicVisitId")
                        .HasColumnType("int");

                    b.Property<int>("ConsentFormId")
                        .HasColumnType("int");

                    b.Property<string>("ConsentFormUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicVisitId")
                        .HasDatabaseName("IX_ClinicVisitConsentForm_ClinicVisitId");

                    b.HasIndex("ConsentFormId")
                        .HasDatabaseName("IX_ClinicVisitConsentForm_ConsentFormId");

                    b.ToTable("clinicvisitconsentforms", (string)null);
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.Hifi5PricingPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int")
                        .HasColumnName("Duration_Months");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<string>("ExtensionAllowed")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Extension_Allowed");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Frequency");

                    b.Property<string>("HsnNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("HSN");

                    b.Property<string>("IncludesPhysio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Includes_Physio");

                    b.Property<int>("PhysioSessions")
                        .HasColumnType("int")
                        .HasColumnName("Physio_Sessions");

                    b.Property<decimal>("PriceInr")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Price_INR");

                    b.Property<string>("ProgramCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Program_Category");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Program_Name");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int")
                        .HasColumnName("Total_Sessions");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("hifi5PricingPackages");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.High5Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PackageDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<TimeSpan>("PackageTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("CoachId");

                    b.HasIndex("UserId");

                    b.ToTable("High5Appointments");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.High5ChocheForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsSend")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("UserId");

                    b.ToTable("high5ChocheForms");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Labs.LabAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("EntityName")
                        .HasColumnType("longtext");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("Notifications")
                        .HasColumnType("longtext");

                    b.Property<int?>("SentToUserId")
                        .HasColumnType("int");

                    b.Property<string>("SentToUserNotifications")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionId")
                        .HasColumnType("longtext");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("labauditlogs");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Labs.LabErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasColumnType("longtext");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("laberrorlogs", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Labs.LabMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<int>("PromotedBy")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LabId", "DeletedBy")
                        .HasDatabaseName("IX_LabMembers_LabId_DeletedBy");

                    b.HasIndex("Id", "LabId", "DeletedBy")
                        .HasDatabaseName("IX_LabMembers_Id_LabId_DeletedBy");

                    b.HasIndex("UserId", "LabId", "DeletedBy")
                        .HasDatabaseName("IX_LabMembers_UserId_LabId_DeletedBy");

                    b.HasIndex("UserId", "LabId", "DeletedBy", "Role")
                        .HasDatabaseName("IX_LabMembers_UserId_LabId_DeletedBy_Role");

                    b.ToTable("labmembers", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Labs.LabOtpEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OtpCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_LabOtpEntry_Email");

                    b.HasIndex("Email", "CreatedAt")
                        .HasDatabaseName("IX_LabOtpEntries_Email_CreatedAt");

                    b.HasIndex("Email", "CreatedAt", "ExpiryTime")
                        .HasDatabaseName("IX_LabOtpEntries_Email_CreatedAt_ExpiryTime");

                    b.ToTable("labotpentries", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Labs.LabResendReports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LabUserReportId")
                        .HasColumnType("int");

                    b.Property<long>("ResendEpochTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("labresendreports", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Labs.LabSignup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<long>("CreatedAtEpoch")
                        .HasColumnType("bigint");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HFID")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LabReference")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_LabSignup_Email");

                    b.HasIndex("HFID")
                        .IsUnique();

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_LabSignup_Id");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_LabSignups_PhoneNumber");

                    b.HasIndex("Pincode")
                        .HasDatabaseName("IX_LabSignups_Pincode");

                    b.HasIndex("Id", "LabReference")
                        .HasDatabaseName("IX_LabSignups_Id_Reference");

                    b.HasIndex("LabReference", "DeletedBy")
                        .HasDatabaseName("IX_LabSignups_LabReference_DeletedBy");

                    b.HasIndex("Id", "Email", "DeletedBy")
                        .HasDatabaseName("IX_LabSignups_Id_Email_DeletedBy");

                    b.ToTable("labsignups", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Labs.LabSuperAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<int>("IsMain")
                        .HasColumnType("int");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id", "UserId")
                        .HasDatabaseName("IX_LabSuperAdmins_Id_UserId");

                    b.HasIndex("LabId", "IsMain")
                        .HasDatabaseName("IX_LabSuperAdmins_LabId_IsMain");

                    b.HasIndex("UserId", "LabId", "IsMain")
                        .HasDatabaseName("IX_LabSuperAdmins_UserId_LabId_IsMain");

                    b.ToTable("labsuperadmins", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Labs.LabUserReports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Resend")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("labuserreports", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.CountryLists2", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("countryname")
                        .HasColumnType("longtext");

                    b.Property<string>("dialingcode")
                        .HasColumnType("longtext");

                    b.Property<string>("isocode")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("countrylist2", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CountryCallingCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<long>("CreatedEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("DOB")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmergencyContactCountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("EmergencyContactPhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("HeightFeet")
                        .HasColumnType("int");

                    b.Property<int?>("HeightInches")
                        .HasColumnType("int");

                    b.Property<string>("HfId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PatientId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Relation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserReference")
                        .HasColumnType("int");

                    b.Property<float?>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("users", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserDynamicAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AllergyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsAllergic")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("userdynamicallergies", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserDynamicDiseaseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiseaseTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("FatherSide")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MotherSide")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Myself")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("userdynamicdiseaserecords", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserDynamicDiseaseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("userdynamicdiseasetypes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserMedicationAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StaticAllergyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaticAllergyId");

                    b.HasIndex("UserId");

                    b.ToTable("usermedicationallergies", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuditLogId")
                        .HasColumnType("int");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("DismissedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<long?>("ReadAt")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogId");

                    b.ToTable("usernotifications", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<long>("EpochTime")
                        .HasColumnType("bigint");

                    b.Property<decimal>("FileSize")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("LabId")
                        .HasColumnType("int");

                    b.Property<int?>("LabUserReportId")
                        .HasColumnType("int");

                    b.Property<int>("ReportCategory")
                        .HasColumnType("int");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ReportUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("userreports", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserSocialHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AlcoholFrequency")
                        .HasColumnType("int");

                    b.Property<int?>("CaffeineFrequency")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseFrequency")
                        .HasColumnType("int");

                    b.Property<int?>("SmokingFrequency")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usersocialhistories", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserStaticAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AllergyType")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllergic")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("userstaticallergies", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserStaticDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiseaseType")
                        .HasColumnType("int");

                    b.Property<bool>("FatherSide")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MotherSide")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Myself")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("userstaticdiseases", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("EndEpoch")
                        .HasColumnType("bigint");

                    b.Property<long>("StartEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usersubscriptions", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserSurgeryDetails", b =>
                {
                    b.Property<int>("user_surgery_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("drname")
                        .HasColumnType("longtext");

                    b.Property<string>("hostname")
                        .HasColumnType("longtext");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("user_surgery_details")
                        .HasColumnType("longtext");

                    b.Property<string>("user_surgery_year")
                        .HasColumnType("longtext");

                    b.HasKey("user_surgery_id");

                    b.ToTable("user_surgery_details", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.BlacklistedToken", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicAppointment", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinics")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicEnquiry", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicEnquiryCoach", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicMemberRecord", "CoachRecord")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicEnquiry", "ClinicEnquiry")
                        .WithMany()
                        .HasForeignKey("EnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClinicEnquiry");

                    b.Navigation("CoachRecord");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicGoogleToken", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicMember", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "PromotedByUser")
                        .WithMany()
                        .HasForeignKey("PromotedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("CreatedByUser");

                    b.Navigation("PromotedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicMemberRecord", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicMember", "ClinicMember")
                        .WithMany()
                        .HasForeignKey("ClinicMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("ClinicMember");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicPatientMedicalHistory", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicPatient", "ClinicPatient")
                        .WithMany()
                        .HasForeignKey("ClinicPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("ClinicPatient");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicPatientRecord", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicVisit", "Visit")
                        .WithMany()
                        .HasForeignKey("ClinicVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicPatient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Patient");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicPrescription", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicPrescriptionNotes", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicRecordCounter", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicSuperAdmin", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicTreatment", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicVisit", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany("Visits")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicPatient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("ClinicPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicVisitConsentForm", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicVisit", "Visit")
                        .WithMany("ConsentFormsSent")
                        .HasForeignKey("ClinicVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicConsentForm", "ConsentForm")
                        .WithMany()
                        .HasForeignKey("ConsentFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsentForm");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.Hifi5PricingPackage", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.High5Appointment", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicMember", "CoachMember")
                        .WithMany()
                        .HasForeignKey("CoachId");

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("CoachMember");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.High5ChocheForm", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinics")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinics");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserDynamicAllergy", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserDynamicDiseaseRecord", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Users.UserDynamicDiseaseType", "DiseaseType")
                        .WithMany()
                        .HasForeignKey("DiseaseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiseaseType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserMedicationAllergy", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Users.UserStaticAllergy", "UserStaticAllergy")
                        .WithMany("MedicationAllergies")
                        .HasForeignKey("StaticAllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserStaticAllergy");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserNotification", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Labs.LabAuditLog", "AuditLog")
                        .WithMany()
                        .HasForeignKey("AuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditLog");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserReport", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", "Clinics")
                        .WithMany()
                        .HasForeignKey("ClinicId");

                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserSocialHistory", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserStaticAllergy", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserStaticDisease", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserSubscription", b =>
                {
                    b.HasOne("HFiles_Backend.Domain.Entities.Users.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicPatient", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicSignup", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Clinics.ClinicVisit", b =>
                {
                    b.Navigation("ConsentFormsSent");
                });

            modelBuilder.Entity("HFiles_Backend.Domain.Entities.Users.UserStaticAllergy", b =>
                {
                    b.Navigation("MedicationAllergies");
                });
#pragma warning restore 612, 618
        }
    }
}
